# See https://mherman.org/blog/logging-in-kubernetes-with-elasticsearch-Kibana-fluentd/#elastic

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: kibana
  labels:
    app: kibana
    component: elasticsearch
spec:
  selector:
    matchLabels:
      app: kibana
      component: elasticsearch
  template:
    metadata:
      labels:
        app: kibana
        component: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kibana
  labels:
    app: kibana
    component: elasticsearch
spec:
  selector:
    app: kibana
    component: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: http
