# File: ./kubernetes/traefik/05-Services.yaml
# https://doc.traefik.io/traefik/v2.4/user-guides/crd-acme/#services
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik

spec:
  ports:
    - protocol: TCP
      name: web
      port: 8000
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 4443
  selector:
    app: traefik
    component: ingress-controller
  type: LoadBalancer
