# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: internal-whitelist
#   namespace: keycloak
# spec:
#   ipWhiteList:
#     sourceRange:
#       - 127.0.0.1/32
#       - 192.168.255.0/24
# ---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: internal-route
  namespace: keycloak
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`kube-keycloak.bar.com`)
    # kind: Rule
    services:
    - name: keycloak-http
      # kind: Service
      namespace: keycloak
      port: 443
#   middlewares:
#   - name: internal-whitelist
#     namespace: keycloak
  tls:
    passthrough: true