apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: {{vpn.entryPointIp}}
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: {{cluster.name}}
networking:
  podSubnet: "10.244.0.0/16"
apiServer:
  extraArgs:
    audit-policy-file: /etc/kubernetes/audit-policy.yaml
    audit-log-path: {{audit.sourceLogDir}}/{{audit.sourceLogFile}}
  extraVolumes:
    - name: audit-policy
      hostPath: {{audit.policyFile}}
      mountPath: /etc/kubernetes/audit-policy.yaml # See apiServer.extraArgs.audit-policy-file
      readOnly: true
    - name: audit-log
      hostPath: {{audit.sourceLogDir}}
      mountPath: {{audit.sourceLogDir}}
      pathType: DirectoryOrCreate
      readOnly: false